name: Consume changesets

on:
  push:
    branches:
      # TODO revert back to develop before merging this
      - feature/readme-generator-script

jobs:
  consume-changesets:
    name: Consume changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # TODO remove [TEST]
          version: yarn changeset version
          title: '[TEST] Consume changesets'
          commit: '[TEST] Consume changesets'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate READMEs
        run: |
          yarn setup
          yarn generate:readme -a -v
          README_GENERATOR_EXIT_CODE=$?

          if [ $README_GENERATOR_EXIT_CODE -ne 0 ]; then
              echo "README(s) could not be generated. Aborting commit."
              exit 1
          else
              git add *
              yarn lint-staged
              git commit --amend --no-edit
              git push --force
              echo "README(s) generated successfully."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
